steps:
- name: gcr.io/cloud-builders/git
  args:
    - '-c'
    - |
      git tag  # Prints nothing
      git describe --tags --always  # Prints hash only
      git log  # Prints only the last commit message
